[book]
authors = ["DCS-Web-Dashboard Team"]
language = "en"
src = "src"
title = "DCS-Web-Dashboard Documentation"

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/sevenfifty777/DCS-Web-Dashboard"
edit-url-template = "https://github.com/sevenfifty777/DCS-Web-Dashboard/edit/main/docs/{path}"
